-- Create Categories Table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Categories
alter table categories enable row level security;
create policy "Enable read access for all users" on categories for select using (true);
create policy "Enable insert for authenticated users only" on categories for insert with check (auth.role() = 'authenticated');

-- Seed Default Categories
insert into categories (name) values
  ('General'),
  ('Bebidas'),
  ('Almacén'),
  ('Golosinas'),
  ('Cigarrillos'),
  ('Limpieza'),
  ('Lácteos'),
  ('Panadería')
on conflict (name) do nothing;

-- Add cost_price to sale_items
alter table sale_items add column if not exists cost_price numeric default 0;

-- Create Profit Analysis RPC
create or replace function get_daily_measures()
returns json
language plpgsql
security definer
as $$
declare
  total_sales numeric;
  total_cost numeric;
  total_count integer;
  start_of_day timestamp with time zone;
  end_of_day timestamp with time zone;
begin
  -- Define day boundaries (UTC)
  start_of_day := date_trunc('day', now());
  end_of_day := start_of_day + interval '1 day';

  -- Calculate totals
  select 
    coalesce(sum(s.total_amount), 0),
    count(s.id)
  into 
    total_sales,
    total_count
  from sales s
  where s.created_at >= start_of_day and s.created_at < end_of_day
  and s.status = 'COMPLETED';

  -- Calculate costs (joining with sale_items)
  select 
    coalesce(sum(si.cost_price * si.quantity), 0)
  into 
    total_cost
  from sale_items si
  join sales s on si.sale_id = s.id
  where s.created_at >= start_of_day and s.created_at < end_of_day
  and s.status = 'COMPLETED';

  return json_build_object(
    'total_sales', total_sales,
    'total_cost', total_cost,
    'net_profit', total_sales - total_cost,
    'transaction_count', total_count,
    'date', start_of_day
  );
end;
$$;
